# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "WeStep" do

pod 'AFNetworking', '~> 2.2'
pod 'DRDynamicSlideShow'

end

target "WeStepTests" do

end

