// Generated by CoffeeScript 1.7.1
'use strict';
var step;

step = angular.module('stepApp', ['ngCookies', 'ngResource', 'ngSanitize', 'ngRoute', 'blueimp.fileupload']);

step.config(function($routeProvider, $locationProvider, $httpProvider, fileUploadProvider) {
  $routeProvider.when('/', {
    templateUrl: 'partials/main',
    controller: 'MainCtrl'
  }).when('/login', {
    templateUrl: 'partials/login',
    controller: 'LoginCtrl'
  }).when('/signup', {
    templateUrl: 'partials/signup',
    controller: 'SignupCtrl'
  }).when('/settings', {
    templateUrl: 'partials/settings',
    controller: 'SettingsCtrl',
    authenticate: true
  }).when('/test', {
    templateUrl: 'partials/test1',
    controller: 'MainCtrl'
  }).otherwise({
    redirectTo: '/'
  });
  $locationProvider.html5Mode(true);
  $httpProvider.interceptors.push([
    '$q', '$location', function($q, $location) {
      return {
        responseError: function(response) {
          if (response.status === 401) {
            $location.path('/login');
            return $q.reject(response);
          } else {
            return $q.reject(response);
          }
        }
      };
    }
  ]);
  delete $httpProvider.defaults.headers.common['X-Requested-With'];
  return fileUploadProvider.defaults.redirect = window.location.href.replace(/\/[^\/]*$/, '/cors/result.html?%s');
});

step.run(function($rootScope, $location, Auth) {
  return $rootScope.$on('$routeChangeStart', function(event, next) {
    if (next.authenticate && !Auth.isLoggedIn()) {
      return $location.path('/login');
    }
  });
});
