// Generated by CoffeeScript 1.7.1
var addTag;

window.onload = function() {
  var garbag, i, tag, tags, _i, _len;
  garbag = document.getElementById("garbag");
  tags = document.getElementsByClassName("tags");
  tag = null;
  for (_i = 0, _len = tags.length; _i < _len; _i++) {
    i = tags[_i];
    i.ondragstart = function(ev) {
      ev.dataTransfer.setData("text", ev.target.innerHTML);
      tag = ev.target;
      garbage.style.borderStyle = "solid";
      garbage.style.borderColor = "#66afe9";
      garbage.style.boxShadow = "inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)";
      return true;
    };
    i.ondragend = function(ev) {
      tag = null;
      garbage.style.borderStyle = "dotted";
      garbage.style.borderColor = "#ccc";
      garbage.style.boxShadow = "none";
      return false;
    };
  }
  garbage.ondragenter = function(ev) {
    ev.preventDefault();
    return true;
  };
  garbage.ondragover = function(ev) {
    ev.preventDefault();
    return true;
  };
  garbage.ondragleave = function(ev) {
    ev.preventDefault();
    return true;
  };
  return garbage.ondrop = function(ev) {
    if (tag) {
      tag.parentNode.removeChild(tag);
    }
    ev.preventDefault();
    return false;
  };
};

addTag = function() {
  var c, p, tagV, tags;
  p = document.getElementsByClassName("tag");
  c = document.createElement("span");
  tagV = document.getElementById("addTag");
  c.className = "btn btn-info btn-xs tags";
  c.title = "拖拽我";
  c.draggable = "true";
  c.innerHTML = tagV.value;
  c.style.marginRight = "5px";
  p[0].appendChild(c);
  return tags = document.getElementsByClassName("tags");
};
