// Generated by CoffeeScript 1.7.1
var addTag, tag;

tag = null;

$(function() {
  var garbage, i, tags, _i, _ref;
  garbage = ($("#garbage"))[0];
  tags = $(".tags");
  for (i = _i = 0, _ref = tags.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    tags[i].ondragstart = function(ev) {
      ev.dataTransfer.setData("text", ev.target.innerHTML);
      tag = ev.target;
      garbage.style.borderStyle = "solid";
      garbage.style.borderColor = "#66afe9";
      garbage.style.boxShadow = "inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)";
      return console.log("haha");
    };
    tags[i].ondragend = function(ev) {
      tag = null;
      garbage.style.borderStyle = "dotted";
      garbage.style.borderColor = "#ccc";
      return garbage.style.boxShadow = "none";
    };
  }
  garbage.ondragenter = function(ev) {
    return ev.preventDefault();
  };
  garbage.ondragover = function(ev) {
    return ev.preventDefault();
  };
  garbage.ondragleave = function(ev) {
    return ev.preventDefault();
  };
  return garbage.ondrop = function(ev) {
    if (tag) {
      tag.parentNode.removeChild(tag);
      return ev.preventDefault();
    }
  };
});

addTag = function() {
  var c, p;
  p = $(".tag");
  c = document.createElement("span");
  c.className = "btn btn-info btn-xs tags";
  c.title = "拖拽我";
  c.draggable = "true";
  c.innerHTML = (document.getElementById("addTag")).value;
  c.style.marginRight = "5px";
  p[0].appendChild(c);
  c.ondragstart = function(ev) {
    ev.dataTransfer.setData("text", ev.target.innerHTML);
    return tag = ev.target;
  };
  c.ondragend = function(ev) {
    return tag = null;
  };
  return console.log();
};
