// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('stepApp').controller('ScenceCtrl', function($scope, $http) {
  return $http.get('/api/awesomeThings').success(function(awesomeThings) {
    return $scope.awesomeThings = awesomeThings;
  });
});
