// Generated by CoffeeScript 1.7.1
'use strict';
var CitySchema, Schema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

CitySchema = new Schema({
  name: String,
  scenes: []
});

module.exports = mongoose.model('City', CitySchema);
