// Generated by CoffeeScript 1.7.1
'use strict';
var SceneSchema, Schema, crypto, mongoose;

mongoose = require('mongoose');

crypto = require('crypto');

Schema = mongoose.Schema;

SceneSchema = new Schema({
  name: String,
  name_en: String,
  city_cn: String,
  category: String,
  alias: [],
  location: [
    new Schema({
      latitude: String,
      longitude: String,
      geo: String,
      area: String,
      addr: String
    })
  ],
  ext: [
    new Schema({
      description: String,
      images: [],
      audio: String
    })
  ]
});

module.exports = mongoose.model('Scene', SceneSchema);
