// Generated by CoffeeScript 1.7.1
'use strict';
var City, cityUtil, mongoose;

mongoose = require('mongoose');

cityUtil = require('../util/cityUtil');

City = mongoose.model('City');

exports.show = function(req, res, next) {
  var cities, province;
  province = req.param('province');
  if (province) {
    cities = cityUtil.get_cities_by_province(province);
    res.send(JSON.stringify({
      status: 'success',
      data: cities
    }));
    return;
  } else {

  }
};

exports.show_city_by_name = function(req, res, next) {
  var name;
  name = req.params.name;
  console.log(name);
  City.find({
    name: name
  }, function(err, scene) {
    if (err) {
      return next(err);
    }
    if (!scene) {
      return res.send(404);
    }
    res.send({
      status: 'success',
      data: scene
    });
  });
};

exports.get_cities = function(req, res, next) {
  var name, tmp;
  name = req.params.province;
  console.log("name");
  tmp = cityUtil.get_cities_by_province(name);
  console.log(tmp);
  res.send({
    status: 'success',
    data: tmp
  });
};
