// Generated by CoffeeScript 1.7.1
'use strict';
var City, mongoose;

mongoose = require('mongoose');

City = mongoose.model('City');

exports.show = function(req, res, next) {
  City.find(function(err, city) {
    if (err) {
      return next(err);
    }
    if (!city) {
      return res.send(404);
    }
    res.send({
      status: 'success',
      data: city
    });
  });
};

exports.show_city_by_name = function(req, res, next) {
  var name;
  name = req.params.name;
  console.log(name);
  City.find({
    name: name
  }, function(err, scene) {
    if (err) {
      return next(err);
    }
    if (!scene) {
      return res.send(404);
    }
    res.send({
      status: 'success',
      data: scene
    });
  });
};
