// Generated by CoffeeScript 1.7.1
'use strict';
var City, Scene, cities, cityUtil, mongoose;

mongoose = require('mongoose');

cityUtil = require('../util/cityUtil');

City = mongoose.model('City');

Scene = mongoose.model('Scene');

cities = {};

cities.scenes = {
  list: function(req, res, next) {
    var city;
    city = req.params.city;
    City.find({
      name: city
    }, function(err, scene_list) {
      if (err) {
        return next(err);
      }
      if (!scene_list) {
        return res.send(404);
      }
      res.send({
        status: 'success',
        data: scene_list
      });
    });
  },
  show: function(req, res, next) {
    var city, scene_name;
    city = req.params.city;
    scene_name = req.params.scenes;
    console.log("City: " + city + " | SceneName: " + scene_name);
    Scene.find({
      name: scene_name
    }, function(err, scene) {
      if (err) {
        return next(err);
      }
      if (!scene) {
        return res.send(404);
      }
      console.log(scene);
      res.send(JSON.stringify({
        status: 'success',
        data: scene
      }));
    });
  },
  save: function(req, res, next) {
    res.send(JSON.stringify({
      status: 'success',
      data: {}
    }));
  },
  children: {
    show: function() {},
    save: function() {}
  }
};

module.exports = cities;
