// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("stepApp").factory("User", function($resource) {
  return $resource("/api/users/:id", {
    id: "@id"
  }, {
    update: {
      method: "PUT",
      params: {}
    },
    get: {
      method: "GET",
      params: {
        id: "me"
      }
    }
  });
});
