// Generated by CoffeeScript 1.7.1
'use strict';
var app, config, db, exports, express, fs, modelsPath, mongoose, passport, path;

express = require('express');

path = require('path');

fs = require('fs');

mongoose = require('mongoose');


/*
 * 主程序入口
 */

process.env.NODE_ENV = process.env.NODE_ENV || 'development';

config = require('./lib/config/config');

db = mongoose.connect(config.mongo.uri, config.mongo.options);

modelsPath = path.join(__dirname, 'lib/models');

fs.readdirSync(modelsPath).forEach(function(file) {
  if (/(.*)\.(js$)/.test(file)) {
    return require(modelsPath + '/' + file);
  }
});

require('./lib/config/dummydata');

passport = require('./lib/config/passport');

app = express();

require('./lib/config/express')(app);

require('./lib/routes')(app);

app.listen(config.port, config.ip, function() {
  return console.log("Express server listening on " + config.ip + ":" + config.port + ", in " + (app.get('env')) + " mode");
});

exports = module.exports = app;
