// Generated by CoffeeScript 1.7.1
'use strict';
var api, index, middleware, session, users;

api = require('../controllers/api');

index = require('../controllers');

users = require('../controllers/users');

session = require('../controllers/session');

middleware = require('../middleware');

module.exports = function(app) {
  app.route('/api/awesomeThings').get(api.awesomeThings);
  app.route('/api/users').get(users.create).put(users.changePassword);
  app.route('/api/users/me').get(users.me);
  app.route('/api/users/:id').get(users.show);
  app.route('/api/session').post(session.login)["delete"](session.logout);
  app.route('/api/jia').get(api.jia);
  app.route('/api/*').get(function(req, res) {
    return res.send(404);
  });
  app.route('/partials/*').get(index.partials);
  return app.route('/*').get(middleware.setUserCookie, index.index);
};
