// Generated by CoffeeScript 1.7.1
'use strict';

/*
Removes server error when user updates input
 */
angular.module('stepApp').directive('mongooseError', function() {
  return {
    restrict: 'A',
    require: 'ngModel',
    link: function(scope, element, attrs, ngModel) {
      return element.on('keydown', function() {
        return ngModel.$setValidity('mongoose', true);
      });
    }
  };
});
